### ISSUE TITLE
Creating conversation with single user raise 500

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat#139]
Code used to trigger the 500

```
const skygearChat = require('skygear-chat');
skygear.auth.loginWithUsername('rickmak', '123456').then((user) => {
console.log('log in ok');

const conversationOptions = {
  distinctByParticipants: true
};
const conversationMeta = {};

console.log('Conversation creating!');
skygearChat.createConversation(
  [null, skygear.auth.currentUser],
  this.nom_docteur,
  conversationMeta,
  conversationOptions
).then((conversation)=>{
  console.log('Conversation created!', conversation);
}).catch((err)=> {
  console.log('Failed to create conversation');
});
});

```

Stack trace

```
2017-09-26 14:24:48,259 ERROR [skygear.transmitter.common:57][Thread-8] Error occurred processing request
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/skygear/transmitter/common.py", line 40, in wrapper
    return dict(result=f(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/skygear/transmitter/common.py", line 100, in call_func
    return self.op(obj, param.get('args', {}))
  File "/usr/lib/python3.5/site-packages/skygear/transmitter/common.py", line 174, in op
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/chat/conversation_handlers.py", line 356, in create_conversation_lambda
    options)
  File "/usr/lib/python3.5/site-packages/chat/conversation_handlers.py", line 278, in handle_create_conversation_lambda
    User.deserialize(p).id.key for p in participants]
  File "/usr/lib/python3.5/site-packages/chat/conversation_handlers.py", line 278, in <listcomp>
    User.deserialize(p).id.key for p in participants]
  File "/usr/lib/python3.5/site-packages/chat/user.py", line 31, in deserialize
    name = record.get('name', None)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by rickmak** [comment]
After discuss with @howawong we came up with following:

1. no 500 stack trace should throw to user
1. regards `null` at user array as `InvalidArgument`
